[global]
daemonize = no

[www]
listen = /var/run/phpx-fpm.sock
listen.mode = 0666

access.format='[%{%Y-%m-%d %H:%M:%S}T] %{HTTP_X_FORWARDED_FOR}e %{REMOTE_ADDR}e %s "%m %{REQUEST_URI}e" %{SERVER_PROTOCOL}e %l %ds %{HTTP_REFERER}e %{HTTP_USER_AGENT}e %{HTTP_X_REQUEST_ID}e'
